version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: video-library-api
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/prisma:/usr/src/app/prisma
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/usr/src/app/prisma/dev.db
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: video-library-web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    command: yarn dev --host
    depends_on:
      - backend
    restart: unless-stopped 